# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nmiller/src/glib-examples

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nmiller/src/glib-examples

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nmiller/src/glib-examples/CMakeFiles /home/nmiller/src/glib-examples/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nmiller/src/glib-examples/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named interface

# Build rule for target.
interface: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 interface
.PHONY : interface

# fast build rule for target.
interface/fast:
	$(MAKE) -f CMakeFiles/interface.dir/build.make CMakeFiles/interface.dir/build
.PHONY : interface/fast

#=============================================================================
# Target rules for targets named children

# Build rule for target.
children: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 children
.PHONY : children

# fast build rule for target.
children/fast:
	$(MAKE) -f CMakeFiles/children.dir/build.make CMakeFiles/children.dir/build
.PHONY : children/fast

children.o: children.c.o

.PHONY : children.o

# target to build an object file
children.c.o:
	$(MAKE) -f CMakeFiles/children.dir/build.make CMakeFiles/children.dir/children.c.o
.PHONY : children.c.o

children.i: children.c.i

.PHONY : children.i

# target to preprocess a source file
children.c.i:
	$(MAKE) -f CMakeFiles/children.dir/build.make CMakeFiles/children.dir/children.c.i
.PHONY : children.c.i

children.s: children.c.s

.PHONY : children.s

# target to generate assembly for a file
children.c.s:
	$(MAKE) -f CMakeFiles/children.dir/build.make CMakeFiles/children.dir/children.c.s
.PHONY : children.c.s

interface.o: interface.c.o

.PHONY : interface.o

# target to build an object file
interface.c.o:
	$(MAKE) -f CMakeFiles/interface.dir/build.make CMakeFiles/interface.dir/interface.c.o
.PHONY : interface.c.o

interface.i: interface.c.i

.PHONY : interface.i

# target to preprocess a source file
interface.c.i:
	$(MAKE) -f CMakeFiles/interface.dir/build.make CMakeFiles/interface.dir/interface.c.i
.PHONY : interface.c.i

interface.s: interface.c.s

.PHONY : interface.s

# target to generate assembly for a file
interface.c.s:
	$(MAKE) -f CMakeFiles/interface.dir/build.make CMakeFiles/interface.dir/interface.c.s
.PHONY : interface.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... interface"
	@echo "... children"
	@echo "... children.o"
	@echo "... children.i"
	@echo "... children.s"
	@echo "... interface.o"
	@echo "... interface.i"
	@echo "... interface.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

